name: Build and Deploy

on:
  push:
    branches:
     # - main 
     - none # to temporary disable action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'  # Specify your Node.js version here
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build  # or your build script
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages  # deploying to gh-pages branch
        FOLDER: public  # or the folder where your build output is located
        CLEAN: true  # Automatically remove deleted files from the deployment
